name: Build Wine_CX for MacOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup x86_64 Homebrew
      run: |
        sudo mkdir -p /usr/local/{bin,Cellar}
        sudo chown -R $(whoami) /usr/local
        cd /usr/local
        git clone https://github.com/Homebrew/brew Homebrew
        eval "$(/usr/local/Homebrew/bin/brew shellenv)"
        echo "HOMEBREW_CELLAR=/usr/local/Cellar" >> $GITHUB_ENV
        echo "HOMEBREW_PREFIX=/usr/local" >> $GITHUB_ENV

    - name: Speed up Homebrew
      run: |
        echo "HOMEBREW_NO_INSTALL_CLEANUP=1" >> $GITHUB_ENV
        echo "HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1" >> $GITHUB_ENV
        echo "HOMEBREW_NO_AUTO_UPDATE=1" >> $GITHUB_ENV
        brew update --quiet

    - name: Install essential dependencies
      run: |
        arch -x86_64 /usr/local/Homebrew/bin/brew install --quiet \
          svn \
          bison \
          flex \
          gcc \
          pkgconfig

    - name: Install library dependencies
      run: |
        arch -x86_64 /usr/local/Homebrew/bin/brew install --quiet \
          mingw-w64 \
          freetype \
          gnutls \
          libpng \
          libxslt \
          gettext

    # Устанавливаем gstreamer отдельно, так как он требует netpbm
    - name: Install gstreamer
      run: |
        arch -x86_64 /usr/local/Homebrew/bin/brew install --quiet \
          gstreamer \
          gst-plugins-base \
          gst-plugins-good || true  # игнорируем ошибки gstreamer

    - name: Setup environment
      run: |
        echo "PATH=/usr/local/bin:/usr/local/opt/bison/bin:/usr/local/opt/freetype/bin:$PATH" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=/usr/local/opt/freetype/lib/pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV
        echo "LDFLAGS=-L/usr/local/opt/bison/lib -L/usr/local/opt/freetype/lib" >> $GITHUB_ENV
        echo "CPPFLAGS=-I/usr/local/opt/bison/include -I/usr/local/opt/freetype/include/freetype2" >> $GITHUB_ENV
        echo "FREETYPE_CFLAGS=-I/usr/local/opt/freetype/include/freetype2" >> $GITHUB_ENV
        echo "FREETYPE_LIBS=-L/usr/local/opt/freetype/lib -lfreetype" >> $GITHUB_ENV

    - name: Clone Wine repository
      run: |
        git clone https://github.com/wine-mirror/wine.git
        cd wine

    - name: Create build directory
      run: |
        mkdir -p wine/config
        mkdir -p wine/build

    - name: Configure Wine
      run: |
        cd wine/config
        PATH="/usr/local/opt/bison/bin:/usr/local/bin:$PATH" \
        PKG_CONFIG_PATH="/usr/local/opt/freetype/lib/pkgconfig:$PKG_CONFIG_PATH" \
        FREETYPE_CFLAGS="-I/usr/local/opt/freetype/include/freetype2" \
        FREETYPE_LIBS="-L/usr/local/opt/freetype/lib -lfreetype" \
        arch -x86_64 ../configure \
          --prefix="${GITHUB_WORKSPACE}/wine/build" \
          --enable-win64
          CFLAGS="-O2 -I/usr/local/opt/freetype/include/freetype2" \
          CXXFLAGS="-O2" \
          LDFLAGS="-L/usr/local/opt/freetype/lib" \
          YACC="/usr/local/opt/bison/bin/bison"

    - name: Build Wine
      run: |
        cd wine/config
        arch -x86_64 make -j$(sysctl -n hw.ncpu)

    - name: Create artifact
      run: |
        cd "${GITHUB_WORKSPACE}"
        tar czf wine-macos-x64.tar.gz wine/build/

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: wine-macos-x64
        path: wine-macos-x64.tar.gz
        retention-days: 7
