name: Build Wine_CX for MacOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        brew update
        brew install \
          bison \
          flex \
          gcc \
          mingw-w64 \
          pkgconfig \
          gnutls \
          freetype \
          libpng \
          libxslt \
          gstreamer \
          gettext

    - name: Clone Wine repository
      run: |
        git clone https://github.com/wine-mirror/wine.git
        cd wine

    - name: Configure Wine
      run: |
        cd wine
        mkdir build
        cd build
        arch -x86_64 ../configure \
          --prefix="${GITHUB_WORKSPACE}/wine-dist" \
          --enable-win64 \
          CFLAGS="-O2" \
          CXXFLAGS="-O2"

    - name: Build Wine
      run: |
        cd wine/build
        arch -x86_64 make -j$(sysctl -n hw.ncpu)

    - name: Install Wine
      run: |
        cd wine/build
        make install

    - name: Create artifact
      run: |
        cd "${GITHUB_WORKSPACE}"
        tar czf wine-macos-x64.tar.gz wine-dist/

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: wine-macos-x64
        path: wine-macos-x64.tar.gz
        retention-days: 7

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: wine-macos-${{ github.sha }}
        release_name: Wine MacOS Build ${{ github.sha }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: wine-macos-x64.tar.gz
        asset_name: wine-macos-x64.tar.gz
        asset_content_type: application/gzip

    - name: Test Wine Installation
      run: |
        cd "${GITHUB_WORKSPACE}/wine-dist/bin"
        ./wine --version
