name: Build Wine for MacOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup x86_64 Homebrew
      run: |
        sudo mkdir -p /usr/local/bin
        sudo mkdir -p /usr/local/Homebrew
        cd /usr/local
        sudo git clone https://github.com/Homebrew/brew Homebrew
        sudo chown -R $(whoami) /usr/local/Homebrew
        eval "$(/usr/local/Homebrew/bin/brew shellenv)"
        brew update

    - name: Install and verify bison
      run: |
        arch -x86_64 /usr/local/Homebrew/bin/brew install bison
        echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH
        /usr/local/opt/bison/bin/bison --version

    - name: Install other dependencies
      run: |
        arch -x86_64 /usr/local/Homebrew/bin/brew install \
          flex \
          gcc \
          mingw-w64 \
          pkgconfig \
          gnutls \
          freetype \
          libpng \
          libxslt \
          gstreamer \
          gettext

    - name: Setup environment
      run: |
        echo "PATH=/usr/local/bin:/usr/local/opt/bison/bin:$PATH" >> $GITHUB_ENV
        echo "HOMEBREW_PREFIX=/usr/local" >> $GITHUB_ENV
        echo "LDFLAGS=-L/usr/local/opt/bison/lib" >> $GITHUB_ENV
        echo "CPPFLAGS=-I/usr/local/opt/bison/include" >> $GITHUB_ENV

    - name: Verify PATH and bison
      run: |
        echo "Current PATH: $PATH"
        which bison
        /usr/local/opt/bison/bin/bison --version

    - name: Clone Wine repository
      run: |
        git clone https://github.com/wine-mirror/wine.git
        cd wine

    - name: Create build directory
      run: |
        mkdir -p wine/config
        mkdir -p wine/build

    - name: Configure Wine
      run: |
        cd wine/config
        PATH="/usr/local/opt/bison/bin:/usr/local/bin:$PATH" \
        arch -x86_64 ../configure \
          --prefix="${GITHUB_WORKSPACE}/wine/build" \
          --enable-win64 \
          CFLAGS="-O2" \
          CXXFLAGS="-O2" \
          YACC="/usr/local/opt/bison/bin/bison"

    - name: Build Wine
      run: |
        cd wine/config
        arch -x86_64 make -j$(sysctl -n hw.ncpu)

    - name: Install Wine
      run: |
        cd wine/config
        make install

    - name: Create artifact
      run: |
        cd "${GITHUB_WORKSPACE}"
        tar czf wine-macos-x64.tar.gz wine/build/

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: wine-macos-x64
        path: wine-macos-x64.tar.gz
        retention-days: 7

    - name: Create Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: wine-macos-${{ github.sha }}
        release_name: Wine MacOS Build ${{ github.sha }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: wine-macos-x64.tar.gz
        asset_name: wine-macos-x64.tar.gz
        asset_content_type: application/gzip
