name: Build Wine for macOS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-wine:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Homebrew
        run: |
          arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Update PATH for Homebrew
        run: |
          echo "/usr/local/bin" >> $GITHUB_PATH
          echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          arch -x86_64 brew update
          arch -x86_64 brew install \
            bison \
            flex \
            gcc \
            mingw-w64 \
            pkgconfig \
            gnutls \
            freetype \
            libpng \
            libxslt \
            gettext

      - name: Verify bison installation
        run: |
          echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH
          arch -x86_64 bison --version

      - name: Clone Wine repository
        run: |
          git clone https://github.com/LLltirlec/wine_CX-10.0.git wine
          cd wine

      - name: Configure Wine
        run: |
          cd wine/config
          PATH="$(brew --prefix bison)/bin:$PATH" arch -x86_64 ../configure \
            --prefix="${GITHUB_WORKSPACE}/wine/build" \
            --enable-win64 \
            --enable-wine64

      - name: Build Wine
        run: |
          cd wine/config
          arch -x86_64 make -j$(sysctl -n hw.ncpu)

      - name: Install Wine
        run: |
          cd wine/config
          make install

      - name: Create artifact
        run: |
          cd "${GITHUB_WORKSPACE}"
          tar czf wine-macos-x64.tar.gz wine/build/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: wine-macos-x64
          path: wine-macos-x64.tar.gz
          retention-days: 7
